name: CI/CD for Spring Boot Calculator App

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build with Maven
      run: mvn clean install

    - name: Run Unit Tests
      run: mvn test

    # Optional: SonarQube analysis (if using SonarQube)
    # - name: SonarQube Scan
    #   run: mvn sonar:sonar
    #   env:
    #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    #     SONAR_HOST_URL: "https://your-sonarqube-url"
    #     SONAR_PROJECT_KEY: "calculator-app"

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/calculator-app:latest .

    - name: Docker Login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/calculator-app:latest

    # Optional: Kubernetes Deployment Step
    # - name: Set up Kubeconfig
    #   run: |
    #     mkdir -p ~/.kube
    #     echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config

    # - name: Deploy to Kubernetes
    #   run: |
    #     kubectl apply -f k8s/deployment.yaml
    #     kubectl apply -f k8s/service.yaml
