name: Calculator CI Pipeline

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Validate project
      run: mvn validate
        
    - name: Compile application
      run: mvn clean compile
      
    - name: Set up virtual display for GUI tests
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb
        export DISPLAY=:99
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        sleep 3
        
    - name: Run tests in headless mode
      run: mvn test -Djava.awt.headless=true
      env:
        DISPLAY: :99
      continue-on-error: true
      
    - name: Generate test report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Maven Tests
        path: target/surefire-reports/*.xml
        reporter: java-junit
        fail-on-error: false
        
    - name: Build JAR package
      run: mvn package -DskipTests
      
    - name: Verify JAR was created
      run: |
        ls -la target/
        echo "JAR file details:"
        ls -la target/*.jar
        
    - name: Test JAR execution (headless)
      run: |
        echo "Testing main class in headless mode..."
        export DISPLAY=:99
        timeout 10s java -Djava.awt.headless=true -cp target/Calculator-1.0-SNAPSHOT.jar com.houarizegai.calculator.App || echo "GUI app tested (timeout expected)"
      continue-on-error: true
      
    - name: Upload Calculator JAR
      uses: actions/upload-artifact@v4
      with:
        name: calculator-jar
        path: target/Calculator-1.0-SNAPSHOT.jar
        retention-days: 30
        
    - name: Upload complete build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: |
          target/*.jar
          target/classes/
        retention-days: 15
        
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: |
          target/surefire-reports/
          target/test-classes/
        retention-days: 7
